package com.yj.vo;

import java.io.Serializable;

/**
 * board 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** b_no. */
	private int b_no;

	/** title. */
	private String title;

	/** writer. */
	private String writer;

	/** content. */
	private String content;

	/** regdate. */
	private String regdate;

	/** ip. */
	private String ip;

	/** fname. */
	private String fname;

	/** fsize. */
	private int fsize;

	/** b_ref. */
	private int bRef;

	/** b_level. */
	private int bLevel;

	/** b_step. */
	private int bStep;

	/** hit. */
	private int hit;

	public int getB_no() {
		return b_no;
	}

	public void setB_no(int b_no) {
		this.b_no = b_no;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getWriter() {
		return writer;
	}

	public void setWriter(String writer) {
		this.writer = writer;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRegdate() {
		return regdate;
	}

	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public int getFsize() {
		return fsize;
	}

	public void setFsize(int fsize) {
		this.fsize = fsize;
	}

	public int getbRef() {
		return bRef;
	}

	public void setbRef(int bRef) {
		this.bRef = bRef;
	}

	public int getbLevel() {
		return bLevel;
	}

	public void setbLevel(int bLevel) {
		this.bLevel = bLevel;
	}

	public int getbStep() {
		return bStep;
	}

	public void setbStep(int bStep) {
		this.bStep = bStep;
	}

	public int getHit() {
		return hit;
	}

	public void setHit(int hit) {
		this.hit = hit;
	}

	public BoardVo(int b_no, String title, String writer, String content, String regdate, String ip, String fname,
			int fsize, int bRef, int bLevel, int bStep, int hit) {
		super();
		this.b_no = b_no;
		this.title = title;
		this.writer = writer;
		this.content = content;
		this.regdate = regdate;
		this.ip = ip;
		this.fname = fname;
		this.fsize = fsize;
		this.bRef = bRef;
		this.bLevel = bLevel;
		this.bStep = bStep;
		this.hit = hit;
	}

	public BoardVo() {
		super();
	}

	
	
}
